### ISSUE TITLE
Create browser from IGV config?

### ISSUE THREAD

**Issue by riyavsinha** [manzt/pygv#4]
I'd love to be able to make a browser session using a full IGVjs config object, e.g.

```
{
            genome: "hg38",
            locus: "chr8:127,736,588-127,739,371",
            tracks: [
                {
                    "name": "HG00103",
                    "url": "https://s3.amazonaws.com/1000genomes/data/HG00103/alignment/HG00103.alt_bwamem_GRCh38DH.20150718.GBR.low_coverage.cram",
                    "indexURL": "https://s3.amazonaws.com/1000genomes/data/HG00103/alignment/HG00103.alt_bwamem_GRCh38DH.20150718.GBR.low_coverage.cram.crai",
                    "format": "cram"
                }
            ]
        }
```

My understanding is currrently I have to do a couple separate calls for setting the genome and locus first, and then the tracks can be added correct? If so, would you be willing to add a new method/option within the `browse` method for instantiation from a full config object?

**Comment by manzt** [comment]
Hi, I added a new API in v0.1.0 for this use case:

```py
import json
from pygv import Config, Browser

with open('config.json') as f:
    config = json.load(f)
    
Browser(Config(config))
```

**Comment by riyavsinha** [comment]
Amazing, thank you, this is great!! This is definitely important to have more interchangeable configs between normal igv and this I think :)
