### ISSUE TITLE
Running in Marimo

### ISSUE THREAD

**Issue by riyavsinha** [manzt/pygv#6]
Hello! I was trying to run this in Marimo, since it is an anywidget component, but I'm having trouble with it. Would you happen to know if there is some additional information that needs to be declared by pygv for this?

Using just `pygv.browse`:
![Screenshot 2024-12-18 at 2 59 38 PM](https://github.com/user-attachments/assets/c0494fce-8b19-4a62-9f67-1686a02621f1)

Using the `mo.ui.anywidget` marimo method to wrap this for display:
![Screenshot 2024-12-18 at 2 57 39 PM](https://github.com/user-attachments/assets/3f2d79a5-afd6-4ece-82fc-a126fe18e916)

**Comment by manzt** [comment]
Hi there, I believe the latest release should also now work in marimo but haven't been able to test myself. Please let me know.

**Comment by riyavsinha** [comment]
It is rendering now, but quite distorted unfortunately! 😓 Thank you for taking a look at this so quickly though also

![Screenshot 2024-12-18 at 4 07 41 PM](https://github.com/user-attachments/assets/ca8fa95d-859b-4c87-be91-d80b9c71b4fc)

**Comment by manzt** [comment]
ahh i think this might be related to how marimo does styling. i think i can bump igv js and it might work. ill poke around and try to cut a release

**Comment by riyavsinha** [comment]
You were correct, just bumping worked! opened a pr for it :)

**Comment by manzt** [comment]
Awesome, thanks for the PR!

**Comment by manzt** [comment]
I made a release in v0.2 with your changes and the new API bindings to the v3  API. Thanks again!
